---
title: "Design Choice Analyses"
author: "Molly Lewis"
date: "This report was rendered on `r Sys.Date()` and will be automatically re-rendered nightly, reflecting any changes in the data or code."
---
  
## Introduction
Here we look across datasets at four common variables: Method, response mode, depenedent measure, and response mode.

```{r, setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = TRUE)
ggplot2::theme_set(langcog::theme_mikabr(base_family = "Ubuntu"))
source("../dashboard/global.R", chdir = TRUE)
library(metafor)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(purrr)
library(langcog)
```

## Data available for each method variable
Method
```{r}
all_data$method = as.factor(all_data$method)
method.pd = all_data %>%
  group_by(method, dataset) %>%
  filter(n() > 3) %>%
  summarise(n = n(),
            d = mean(d_calc))

ggplot(method.pd, aes(y = n, fill = dataset, x = method)) + 
         geom_bar(stat = "identity") +
         xlab("method") +
         ylab("N effect sizes") +
      theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))
```

Response Mode
```{r}
all_data$response_mode = as.factor(all_data$response_mode)

response.pd = all_data %>%
  group_by(response_mode, dataset) %>%
  summarise(n = n(),
            d = mean(d_calc))

ggplot(response.pd, aes(y = n, fill = dataset, x = response_mode)) + 
         geom_bar(stat = "identity") +
         xlab("response mode") +
         ylab("N effect sizes") +
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))
```

Dependent Measure
```{r}
all_data$dependent_measure= as.factor(all_data$dependent_measure)
dm.pd = all_data %>%
  group_by(dependent_measure, dataset) %>%
  summarise(n = n(),
            d = mean(d_calc))

ggplot(dm.pd, aes(y = n, fill = dataset, x = dependent_measure)) + 
         geom_bar(stat = "identity") +
         xlab("method") +
         ylab("N effect sizes") +
         theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))
```

Participant design
```{r}
all_data$participant_design = as.factor(all_data$participant_design)
participant_design.pd = all_data %>%
  group_by(participant_design, dataset) %>%
  summarise(n = n(),
            d = mean(d_calc))

ggplot(participant_design.pd, aes(y = n, fill = dataset, x = participant_design)) + 
         geom_bar(stat = "identity") +
         xlab("participant design") +
         ylab("N effect sizes") +
      theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))
```

## Method variables by age
```{r} 
age.response_mode.pd = all_data %>%
  mutate(mean_age = cut_width(mean_age,  width= 180, boundary = 0))  %>%
  group_by(mean_age, response_mode) %>%
  summarise(n = n()) %>%
  mutate(prop = n / sum(n))

ggplot(age.response_mode.pd, aes(x = mean_age, y = prop, color = response_mode)) +
  geom_point() +
  geom_line(aes(group = response_mode)) +
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  ggtitle("Response Mode")

ggplot(age.response_mode.pd, aes(x = mean_age, y = n, color = response_mode)) +
  geom_point() +
  geom_line(aes(group = response_mode)) +
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  ggtitle("Response Mode")

age.method.pd = all_data %>%
  mutate(mean_age = cut_width(mean_age,  width= 180, boundary = 0))  %>%
  group_by(mean_age, method) %>%
  summarise(n = n()) %>%
  mutate(prop = n / sum(n))

ggplot(age.method.pd, aes(x = mean_age, y = prop, color = method)) +
  geom_point() +
  geom_line(aes(group = method)) +
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  ggtitle("Method")

ggplot(age.method.pd, aes(x = mean_age, y = n, color = method)) +
  geom_point() +
  geom_line(aes(group = method)) +
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  ggtitle("Method")

age.dm.pd = all_data %>%
  mutate(mean_age = cut_width(mean_age,  width= 180, boundary = 0))  %>%
  group_by(mean_age, dependent_measure) %>%
  summarise(n = n()) %>%
  mutate(prop = n / sum(n))

ggplot(age.dm.pd, aes(x = mean_age, y = prop, color = dependent_measure)) +
  geom_point() +
  geom_line(aes(group = dependent_measure)) +
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  ggtitle("Dependent Measure")

ggplot(age.dm.pd, aes(x = mean_age, y = n, color = dependent_measure)) +
  geom_point() +
  geom_line(aes(group = dependent_measure)) +
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  ggtitle("Dependent Measure")

age.pd.pd = all_data %>%
  mutate(mean_age = cut_width(mean_age,  width= 90, boundary = 0))  %>%
  group_by(mean_age, participant_design) %>%
  summarise(n = n()) %>%
  mutate(prop = n / sum(n))

ggplot(age.pd.pd, aes(x = mean_age, y = prop, color = participant_design)) +
  geom_point() +
  geom_line(aes(group = participant_design)) +
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  ggtitle("Participant Design")

ggplot(age.pd.pd, aes(x = mean_age, y = n, color = participant_design)) +
  geom_point() +
  geom_line(aes(group = participant_design)) +
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  ggtitle("Participant Design")
```

## Effect size by method variables
```{r}
ggplot(method.pd, aes(x = method, y = d, color = dataset)) +
  geom_point(aes(size = n)) +
   geom_line(aes(group = dataset)) + 
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  ggtitle("Method")

ggplot(response.pd, aes(x = response_mode, y = d, color = dataset)) +
  geom_point(aes(size = n)) +
   geom_line(aes(group = dataset)) + 
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  ggtitle("Response Mode")

ggplot(dm.pd, aes(x = dependent_measure, y = d, color = dataset)) +
  geom_point(aes(size = n)) +
   geom_line(aes(group = dataset)) + 
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  ggtitle("Dependent Measure")

ggplot(participant_design.pd, aes(x = participant_design, y = d, color = dataset)) +
  geom_point(aes(size = n)) +
  geom_line(aes(group = dataset)) + 
  theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  ggtitle("Participant Design")
```
