---
title: Synthesis Paper Figures 3 and 4
author: Molly Lewis
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    number_sections: false
    theme: cerulean
    #toc_float: true
    code_folding: hide
---
  

```{r setup, include = F}
rm(list = ls())
source("../../dashboard/global.R", chdir = TRUE)
library(knitr)
library(metafor)
library(directlabels)

opts_chunk$set(echo = T, message = F, warning = F, error = F, cache = T, tidy = F)
```

```{r load data}
# remove inappropriate conditions
all_data <- filter(all_data, dataset != "Statistical word segementation") %>% # incomplete MA
            filter(dataset != "Pointing and vocabulary (longitudinal)") %>%  # longitidinal MA
            filter(is.na(condition_type) | condition_type == "critical") # remove control conditions from labadv

# need to recompute datasets summary data, based on filtered all_data
studies <- all_data %>%
  group_by(dataset) %>%
  summarise(num_experiments = n(),
            num_papers = length(unique(study_ID)))

subjects <- all_data %>%
  rowwise() %>%
  mutate(n_total = sum(c(n_1, n_2), na.rm = TRUE)) %>%
  distinct(dataset, study_ID, same_infant, .keep_all = TRUE) %>%
  group_by(dataset) %>%
  summarise(num_subjects = sum(n_total))

datasets <- datasets %>%
  rename(dataset = name) %>%
  select(-num_experiments, -num_papers, -num_subjects) %>%
  filter(dataset != "Statistical word segementation") %>% 
  filter(dataset != "Pointing and vocabulary (longitudinal)") %>%
  left_join(studies) %>%
  left_join(subjects) %>%
  rename(name = dataset)

# rename pointing and vocabulary 
datasets$name = plyr::mapvalues(datasets$name, from = c("Pointing and vocabulary (concurrent)"), 
                                to = c("Pointing and vocabulary"))

all_data$dataset = plyr::mapvalues(all_data$dataset , from = c("Pointing and vocabulary (concurrent)"),
                                   to = c("Pointing and vocabulary"))
```

Fig 3 data
```{r}
# make levels df
ld.df = data.frame(dataset = datasets$name,
                   domain = c("Prosody", "Words", "Communication", "Sounds",
                              "Sounds", "Sounds", "Sounds", "Sounds", "Words",
                              "Words", "Communication", "Words"))

ld.df$domain = factor(ld.df$domain, levels = c("Prosody","Sounds", "Words", "Communication"))

single_method_datasets = c("Gaze following",
                           "Label advantage in concept learning", 
                           "Mutual exclusivity", 
                           "Pointing and vocabulary",
                           "Online word recognition")

# get model fits
all_data.resid = data.frame()
for (i in 1:length(datasets$name)) {
    d = filter(all_data, dataset == datasets$name[i])
    if (datasets$name[i] %in% single_method_datasets) {
      full.model = rma(d_calc, vi = d_var_calc, data = d)
    } else {
      full.model = rma(d_calc ~ method, vi = d_var_calc, data = d)
    }
  
  d = as.data.frame(rstandard(full.model)$resid) %>%
       cbind(d) %>%
       rename(residual.d = `rstandard(full.model)$resid`) %>%
       mutate(residual.d = residual.d + full.model$b[1]) %>% # add in intercept term
       inner_join(all_data) 
  
  all_data.resid = rbind(all_data.resid,d)
}

# merge in levels
residualized.es = all_data.resid %>%
          left_join(ld.df) %>%
          filter(dataset != "Statistical sound category learning") %>%
          filter(dataset != "Phonotactic learning") %>%
          mutate(age.years = mean_age/365) 
```

Fig 4 data
```{r}
## real data
all_data.f = residualized.es %>%
  select(age.years, dataset, residual.d, n) %>%
  mutate(model = "Observed")

## simulated data
# bottom-up
x = seq(0, 3, .01)
slope = 1.1
y1 = ifelse((log(x - 1) * slope) < 0, NA, log(x - 1) * slope)
y2 = ifelse((log(x) * slope) < 0, NA, log(x) * slope)
y3 = ifelse((log(x + 1) * slope) < 0, NA, log(x + 1) * slope)

# interactive 
y4 = log((x + 1)) * .2
y5 = log((x + 1)) * .5
y6 = log((x + 1)) * 1.1

# ad hoc 
y7 = .2 * x
y8 = dnorm(x, mean = 1.7, sd = .5) 
y9 = log(x + .0001, base = .02) + .3

# merge together simulated data
simulated.development = data.frame(age.years = c(x,x,x,x,x,x,x,x,x),
                                   residual.d = c(y3, y2, y1, y6, y5, y4, y9, y8, y7),
                                   dataset = c(rep(1:3, each = length(x)), rep(1:3, each = length(x)),
                                               rep(1:3, each = length(x))),
                                   model = rep(c("Sequential", "Simultaneous", "Ad hoc"), each = length(x) * 3),
                                   n = 1)

## merge together simulated and real
simulated.development.all = mutate(simulated.development, dataset = as.factor(dataset)) %>%
  rbind(all_data.f) %>%
  mutate(model = ordered(model, levels = c("Sequential", "Simultaneous", "Ad hoc", "Observed")),
         level = ifelse(model != "Observed", dataset, 
                        ifelse(dataset == "Infant directed speech preference", 1,
                               ifelse(dataset == "Pointing and vocabulary" | dataset == "Gaze following", 4, 
                                      ifelse(dataset == "Word segmentation" | dataset == "Vowel discrimination (native)" | dataset == "Vowel discrimination (non-native)", 2, 3)))))

real.levels = levels(simulated.development.all$dataset)
fake.levels = c("1", "2", "3") 

simulated.development.all = simulated.development.all %>%
  mutate(dataset.label = as.factor(dataset)) %>%
  mutate(dataset.label = plyr::mapvalues(dataset.label, from = c("1", "2", "3", "Gaze following",  "Infant directed speech preference", "Label advantage in concept learning", "Mutual exclusivity", "Vowel discrimination (native)", "Vowel discrimination (non-native)", "Sound symbolism" , "Online word recognition" , "Word segmentation"), to = c("","","", "GF", "IDS", "LA", "ME", "VD-N", "VD-NN", "SS", "WR", "WS")))
```

## Fig. 3
### rando colors
```{r, fig.width = 8}
p1 = "#fdbb84" # orange
s1 = "#74c476" # green
s2 = "#f768a1" # pink
s3 = "#6baed6" # blue
w1 = "#8856a7" # purple
w2 = "#31a354" # blue
w3 = "#2ca25f" # green
w4 = "#d95f0e" #brown
c1 = "#980043" #red
c2 = "#08519c" # blue

level.plot = 
  ggplot(residualized.es, aes(x = age.years, y = residual.d, col = dataset)) +
  facet_grid(~ domain) +
  geom_point(aes(size = n), alpha = .1, data = filter(residualized.es, residual.d > -.3 & residual.d < 2 )) +
  geom_smooth(method="lm", se = FALSE, size = 1, fullrange = FALSE, formula = y ~ log(x), data = residualized.es) + 
  xlim(0, 3.1) +
  ylim(-.5, 2.2) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  scale_colour_manual(values=c(c1, p1, w1, w2, w3, c2, w4, s1, s2, s3)) +
  xlab("Age (years)") + 
  ylab("Method-residualized effect size") + 
  theme_bw() + 
  theme(legend.position = "none",
        legend.key = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        axis.line= element_line(size = 3),
        axis.text = element_text(colour = "black", size = 18),
        strip.text.x = element_text(size = 14),
        axis.title = element_text(colour = "black", size = 18),
        strip.background = element_rect(fill="grey"))

direct.label(level.plot, list("top.bumptwice", dl.trans(y = y + 0.1), cex = .7))
```

### color brewer
```{r, fig.width = 8}
  ggplot(residualized.es, aes(x = age.years, y = residual.d, col = dataset)) +
  facet_grid(~ domain) +
  geom_point(aes(size = n), alpha = .14, data = filter(residualized.es, residual.d > -.3 & residual.d < 2 )) +
  geom_smooth(method="lm", se = FALSE, size = 1, fullrange = FALSE, formula = y ~ log(x), data = residualized.es) + 
  xlim(0, 3.1) +
  ylim(-.5, 2.2) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  xlab("Age (years)") + 
  ylab("Method-residualized effect size") + 
  scale_colour_brewer(type = "div", palette = 9) + 
  theme_bw() + 
  theme(legend.position = "none",
        legend.key = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        axis.line= element_line(size = 3),
        axis.text = element_text(colour = "black", size = 18),
        strip.text.x = element_text(size = 14),
        axis.title = element_text(colour = "black", size = 18),
        strip.background = element_rect(fill="grey"))
```

### color brewer
```{r, fig.width = 8}
  ggplot(residualized.es, aes(x = age.years, y = residual.d, col = dataset)) +
  facet_grid(~ domain) +
  geom_point(aes(size = n), alpha = .14, data = filter(residualized.es, residual.d > -.3 & residual.d < 2 )) +
  geom_smooth(method="lm", se = FALSE, size = 1, fullrange = FALSE, formula = y ~ log(x), data = residualized.es) + 
  xlim(0, 3.1) +
  ylim(-.5, 2.2) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  xlab("Age (years)") + 
  ylab("Method-residualized effect size") + 
  scale_colour_brewer(type = "div", palette = 8) + 
  theme_bw() + 
  theme(legend.position = "none",
        legend.key = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        axis.line= element_line(size = 3),
        axis.text = element_text(colour = "black", size = 18),
        strip.text.x = element_text(size = 14),
        axis.title = element_text(colour = "black", size = 18),
        strip.background = element_rect(fill="grey"))
```

### default
```{r, fig.width = 8}
  ggplot(residualized.es, aes(x = age.years, y = residual.d, col = dataset)) +
  facet_grid(~ domain) +
  geom_point(aes(size = n), alpha = .1, data = filter(residualized.es, residual.d > -.3 & residual.d < 2 )) +
  geom_smooth(method="lm", se = FALSE, size = 1, fullrange = FALSE, formula = y ~ log(x), data = residualized.es) + 
  xlim(0, 3.1) +
  ylim(-.5, 2.2) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  xlab("Age (years)") + 
  ylab("Method-residualized effect size") + 
  #scale_colour_brewer(type = "qual", palette = 8) + 
  theme_bw() + 
  theme(legend.position = "none",
        legend.key = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        axis.line= element_line(size = 3),
        axis.text = element_text(colour = "black", size = 18),
        strip.text.x = element_text(size = 14),
        axis.title = element_text(colour = "black", size = 18),
        strip.background = element_rect(fill="grey"))
```

### default2
```{r, fig.width = 8}

pink1 = "#F8766D"
barf = "#D89000"
yellowgreen = "#A3A500" 
green1 = "#39B600" 
green2 = "#00BF7D" 
blue1 = "#00BFC4"
blue2 = "#00B0F6"
purple = "#9590FF"
pink2 = "#E76BF3"
pink3 = "#FF62BC"

  ggplot(residualized.es, aes(x = age.years, y = residual.d, col = as.factor(dataset))) +
  facet_grid(~ domain) +
  geom_point(aes(size = n), alpha = .1, data = filter(residualized.es, residual.d > -.3 & residual.d < 2 )) +
  geom_smooth(method="lm", se = FALSE, size = 1, fullrange = FALSE, formula = y ~ log(x), data = residualized.es) + 
  xlim(0, 3.1) +
  ylim(-.5, 2.2) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  xlab("Age (years)") + 
  ylab("Method-residualized effect size") + 
   scale_colour_manual(values=c(pink2, blue1, purple, green2, pink1, 
                                yellowgreen, barf,  green1, pink3, blue2)) +
  theme_bw() + 
  theme(legend.position = "none",
        legend.key = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        axis.line= element_line(size = 3),
        axis.text = element_text(colour = "black", size = 18),
        strip.text.x = element_text(size = 14),
        axis.title = element_text(colour = "black", size = 18),
        strip.background = element_rect(fill="grey"))
#ggplotColours(n = 10)



#values=c(yellowgreen, pink1, barf, green1, green2, blue1, blue2, purple, pink2, pink3)

#values=
#

                   
 #[2] "Infant directed speech preference"  - pink2
                   
 #[8] "Vowel discrimination (native)"  pink3    
 #[9] "Vowel discrimination (non-native)"  blue1,
#[10] "Word segmentation" green1,

# [3] "Label advantage in concept learning"purple
# [4] "Mutual exclusivity"green2
# [5] "Online word recognition" pink1         
# [7] "Sound symbolism"  barf

# [6] "Pointing and vocabulary" blue2
# [1] "Gaze following"  yellowgreen

```


Fig. 4
```{r, fig.width = 8}
## plot
ggplot(simulated.development.all,
       aes(x = age.years, y = residual.d, col = dataset)) + 
  geom_line(data = filter(simulated.development.all,
                          model != "Observed"), size = 1) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_smooth(data = filter(simulated.development.all, 
                            model == "Observed"), method="lm", 
              se = FALSE, fullrange = FALSE, formula = y~log(x), size = 1) + 
  facet_grid(.~model) +
  #geom_text_repel(aes(label = dataset.label), data = ggrepel.data) +
  scale_colour_manual(values=c( "grey70", "grey35", "grey20", "#F8766D", 
                                "#DB8E00" ,"#AEA200", "#64B200", "#00BD5C" ,"#00C1A7",
                                "#00BADE" ,"#00A6FF", "#B385FF" ,"#EF67EB" ,"#FF63B6","#FF63B6"),
                      breaks = real.levels[real.levels!=fake.levels]) +
  xlab("Age (years)") +
  ylab("Method-residualized effect size") + 
  ylim(-.5, 2.5) +
  xlim(0,3.1) +
  theme_bw() + 
  theme(legend.position = "none",
        legend.key = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.title = element_blank(),
        axis.line= element_line(size = 3),
        axis.text = element_text(colour = "black", size = 18),
        strip.text.x = element_text(size = 14),
        axis.title = element_text(colour = "black", size = 18),
        strip.background = element_rect(fill="grey"))
```

```{r, fig.width = 8}
## plot
ggplot(simulated.development.all,
       aes(x = age.years, y = residual.d, col = dataset)) + 
  geom_line(data = filter(simulated.development.all,
                          model != "Observed"), aes(linetype = as.factor(level))) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_smooth(data = filter(simulated.development.all, 
                            model == "Observed"), method="lm", 
              se = FALSE, fullrange = FALSE, formula = y~log(x), aes(linetype = as.factor(level)), size = .5)+ 
  facet_grid(.~model) +
  #geom_text_repel(aes(label = dataset.label), data = ggrepel.data) +
  scale_colour_manual(values=c( "grey35", "grey35", "grey35", "#F8766D", 
                                "#DB8E00" ,"#AEA200", "#64B200", "#00BD5C" ,"#00C1A7",
                                "#00BADE" ,"#00A6FF", "#B385FF" ,"#EF67EB" ,"#FF63B6","#FF63B6"),
                      breaks = real.levels[real.levels!=fake.levels]) +
  xlab("Age (years)") +
  ylab("Method-residualized effect size") + 
  ylim(-.5, 2.5) +
  xlim(0,3.1) +
  theme_bw() + 
  theme(legend.position = "none",
        legend.key = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.title = element_blank(),
        axis.line= element_line(size = 3),
        axis.text = element_text(colour = "black", size = 18),
        strip.text.x = element_text(size = 14),
        axis.title = element_text(colour = "black", size = 18),
        strip.background = element_rect(fill="grey"))
```

```{r, fig.width = 8}
## plot
ggplot(simulated.development.all,
       aes(x = age.years, y = residual.d, col = dataset)) + 
  geom_line(data = filter(simulated.development.all, model != "Observed"), 
            aes(alpha = level + 2),
            size = 1) +
  geom_line(stat="smooth", 
            data = filter(simulated.development.all, model == "Observed"), 
            aes(alpha = level + 2),
            size = 1,
            method = "lm",
            formula = y~log(x),
            se = FALSE, 
            fullrange = FALSE) + 
  geom_hline(yintercept = 0, linetype = "dashed") +
  facet_grid(.~model) +
  scale_colour_manual(values=c( "grey35", "grey35", "grey35", pink2, blue1, purple, green2, pink1, 
                                yellowgreen, barf,  green1, pink3, blue2),
                      breaks = real.levels[real.levels!=fake.levels])+
  xlab("Age (years)") +
  ylab("Method-residualized effect size") + 
  ylim(-.5, 2.5) +
  xlim(0,3.1) +
  theme_bw() + 
  theme(legend.position = "none",
        legend.key = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.title = element_blank(),
        axis.line= element_line(size = 3),
        axis.text = element_text(colour = "black", size = 18),
        strip.text.x = element_text(size = 14),
        axis.title = element_text(colour = "black", size = 18),
        strip.background = element_rect(fill="grey"))
```

```{r, fig.width = 8}
## plot
ggplot(simulated.development.all,
       aes(x = age.years, y = residual.d, col = dataset)) + 
  geom_line(data = filter(simulated.development.all, model != "Observed"), 
            aes(alpha = level ),
            size = 1) +
  geom_line(stat="smooth", 
            data = filter(simulated.development.all, model == "Observed"), 
            aes(alpha = level ),
            size = 1,
            method = "lm",
            formula = y~log(x),
            se = FALSE, 
            fullrange = FALSE) + 
  scale_alpha(range = c(0.2, 1)) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  facet_grid(.~model) +
  scale_colour_manual(values=c( "grey35", "grey35", "grey35", pink2, blue1, purple, green2, pink1, 
                                yellowgreen, barf,  green1, pink3, blue2),
                      breaks = real.levels[real.levels!=fake.levels])+
  xlab("Age (years)") +
  ylab("Method-residualized effect size") + 
  ylim(-.5, 2.5) +
  xlim(0,3.1) +
  theme_bw() + 
  theme(legend.position = "none",
        legend.key = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.title = element_blank(),
        axis.line= element_line(size = 3),
        axis.text = element_text(colour = "black", size = 18),
        strip.text.x = element_text(size = 14),
        axis.title = element_text(colour = "black", size = 18),
        strip.background = element_rect(fill="grey"))
```

### default2
```{r, fig.width = 8}

pink1 = "#F8766D"
barf = "#D89000"
yellowgreen = "#A3A500" 
green1 = "#39B600" 
green2 = "#00BF7D" 
blue1 = "#00BFC4"
blue2 = "#00B0F6"
purple = "#9590FF"
pink2 = "#E76BF3"
pink3 = "#FF62BC"

  ggplot(residualized.es, aes(x = age.years, y = residual.d, col = as.factor(dataset))) +
  facet_grid(~ domain) +
  geom_point(aes(size = n), alpha = .1, data = filter(residualized.es, residual.d > -.3 & residual.d < 2 )) +
  geom_smooth(method="lm", se = FALSE, size = 1, fullrange = FALSE, formula = y ~ log(x), data = residualized.es) + 
  xlim(0, 3.1) +
  ylim(-.5, 2.2) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  xlab("Age (years)") + 
  ylab("Method-residualized effect size") + 
   scale_colour_manual(values=c(pink2, blue1, purple, green2, pink1, 
                                yellowgreen, barf,  green1, pink3, blue2)) +
  theme_bw() + 
  theme(legend.position = "none",
        legend.key = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        axis.line= element_line(size = 3),
        axis.text = element_text(colour = "black", size = 18),
        strip.text.x = element_text(size = 14),
        axis.title = element_text(colour = "black", size = 18),
        strip.background = element_rect(fill="grey"))
#ggplotColours(n = 10)



#values=c(yellowgreen, pink1, barf, green1, green2, blue1, blue2, purple, pink2, pink3)

#values=
#

                   
 #[2] "Infant directed speech preference"  - pink2
                   
 #[8] "Vowel discrimination (native)"  pink3    
 #[9] "Vowel discrimination (non-native)"  blue1,
#[10] "Word segmentation" green1,

# [3] "Label advantage in concept learning"purple
# [4] "Mutual exclusivity"green2
# [5] "Online word recognition" pink1         
# [7] "Sound symbolism"  barf

# [6] "Pointing and vocabulary" blue2
# [1] "Gaze following"  yellowgreen

```
