---
title: "ES data for network analysis "
author: "Molly Lewis"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
    theme: united
    code_folding: hide
---
  
```{r, setup, include = FALSE}
library(knitr)
library(tidyr)
library(langcog)
library(tidyverse)
library(stringr)
library(knitr)
library(metafor)

# load data
knitr::opts_chunk$set(fig.width = 8, fig.height = 8, echo = TRUE,
                      warning = FALSE, message = FALSE, cache = TRUE)
source("../dashboard/global.R", chdir = TRUE)
```


```{r load data}
# Method
source("../dashboard/global.R", chdir = TRUE)
source("../write-ups/synthesis_paper/paper_analyses/pcurve.R")

# need to recompute datasets summary data, based on filtered all_data
studies <- all_data %>%
  group_by(dataset) %>%
  summarise(num_experiments = n(),
            num_papers = length(unique(study_ID)))

subjects <- all_data %>%
  rowwise() %>%
  mutate(n_total = sum(c(n_1, n_2), na.rm = TRUE)) %>%
  distinct(dataset, study_ID, same_infant, .keep_all = TRUE) %>%
  group_by(dataset) %>%
  summarise(num_subjects = sum(n_total))

datasets <- datasets %>%
  rename(dataset = name) %>%
  select(-num_experiments, -num_papers, -num_subjects) %>%
  left_join(studies) %>%
  left_join(subjects) %>%
  rename(name = dataset)
```


## Meta-Analytic Effect Size
```{r, overall_d}
overall_es <- function(ma_data){
    model = rma(d_calc, d_var_calc, data = ma_data)
    data.frame(dataset = ma_data$short_name[1],
               overall.d = model$b,
               ci_lower = model$ci.lb,
               ci_upper = model$ci.ub)
}

all_ds = all_data %>%
  split(.$short_name) %>%
  map(function(ma_data) overall_es(ma_data)) %>%
  bind_rows() %>%
  mutate(short_name = dataset)

overall_es_age <- function(ma_data){
    model = rma(d_calc ~ mean_age, d_var_calc, data = ma_data)
    data.frame(dataset = ma_data$short_name[1],
               overall.d.age = model$b[1])
}

all_ds_age = all_data %>%
  split(.$short_name) %>%
  map(function(ma_data) overall_es_age(ma_data)) %>%
  bind_rows() %>%
  mutate(short_name = dataset)
```

## Fail-safe-N
```{r, fail_safe_N}
fsn.package.data = all_data %>%
  group_by(dataset) %>%
  summarise(fsn_package = fsn(d_calc, d_var_calc, data = all_data, 
                         target = .01, type="Orwin")$fsnum) %>%
  left_join(datasets %>% select(name, short_name), by= c("dataset" = "name")) %>%
  rename(fsn_string = fsn_package)
```

## Funnel Skew
```{r, funnel_skew}
eggers_tests <- function(ma_data){
    model = rma(d_calc, d_var_calc, data = ma_data) # model
    egg.random = regtest(model) # Egger's test
    data.frame(dataset = ma_data$short_name[1],
               egg.random.z = egg.random$zval,
               egg.random.p = egg.random$pval)
}

eggers.data = all_data %>%
  ungroup() %>%
  split(.$short_name) %>%
  map(function(ma_data) eggers_tests(ma_data)) %>%
  bind_rows()
```


## P-curves
```{r get_pcurves}
ALPHA = .05
P_INCREMENT = .01 

pc.data <- get_all_pc_data(all_data, ALPHA, P_INCREMENT, transform = TRUE) 
# transform flag determines whether p-values are calculated from descriptive statistics 

p.source = pc.data %>%
  select(f.transform, f.value, dataset, study_ID, p_round) %>%
  group_by(dataset) %>%
  summarise(n.total = n(),
            n.transform = length(which(!is.na(f.transform))),
            sig.p = length(which(p_round < ALPHA))) %>%
  mutate(stat_only = ifelse(n.total > n.transform, 1, 0)) %>%
  arrange(-stat_only) %>%
  mutate(prop.ts = 1-n.transform/n.total) %>%
  as.data.frame()
```

```{r, p_curve_skew}
stouffer.data = pc.data %>%
  group_by(dataset) %>%
  do(data.frame(stouffer = stouffer_test(., ALPHA))) %>%
  filter(stouffer.pp.measure == "ppr.full") %>%
  full_join(datasets %>% select(name, short_name), by= c("dataset" = "name")) 
```


Bind together
```{r}
table.data = all_ds %>%
             left_join(all_ds_age, by = "short_name") %>%
             left_join(fsn.package.data, by = "short_name") %>%
             left_join(eggers.data, by = c("short_name" = "dataset")) %>%
             left_join(stouffer.data) %>%
             select(-dplyr::contains("dataset"), -stouffer.sig)

write.csv(table.data, "ES_data_for_networks.csv")
```


