```{r include=FALSE, echo=FALSE}
library(shiny)
knitr::opts_chunk$set(message = FALSE, warning = FALSE, cache = FALSE)
```

## Overview 

MetaLab is a research tool for aggregating across studies in the language 
acquisition literature. Currently, MetaLab contains
`r as.integer(sum(as.numeric(datasets$num_experiments), na.rm = TRUE))` effect sizes across
meta-analyses in `r nrow(datasets)` domains of language acquisition, based on
data from `r as.integer(sum(as.numeric(datasets$num_papers), na.rm = TRUE))` papers collecting
`r as.integer(sum(as.numeric(datasets$num_subjects), na.rm = TRUE))` subjects. These studies
can be used to obtain better estimates of effect sizes across different domains,
methods, and ages. Using our power calculator, researchers can use these
estimates to plan appropriate sample sizes for prospective studies. More
generally, MetaLab can be used as a theoretical tool for exploring patterns in
development across language acquisition domains.

## Documentation 

+ For more information about individual datasets, see the `Datasets` tab.
+ For information about the field structure of the site, see the `Field Specification` tab. 
+ Individual meta-analyses with other available resources also have their own documentation tabs.
+ For information about doing meta-analyses and contributing to MetaLab, see the `Contribute` page.

## Citation

Currently, papers on the system are in preparation. Please contact [metalab-project@googlegroups.com]() for citation information. 

## Caveat

Please note that data and visualizations are under development at the moment (Spring 2016) and should not be taken as definitive.
